import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Carousel from "./components/carousel/carousel";
import UnitKerja from "./components/unit-kerja/unitkerja";
import Profile from "./components/profile/profile";
import Infografis from "./components/infografis/infografis";
import ReccentArticle from "./components/article/reccentarticle";
import ReccentGaleri from "./components/galeri/reccentgaleri";
import Layanan from "./components/layanan/layanan";
import Data from "./components/data/data";
import Beasiswa from "./components/beasiswa/beasiswa";
import Publikasi from "./components/publikasi/publikasi";
import Loader from "@/components/loader/loader";
import MediaSosial from "./components/media-sosial/media-sosial";
import Banner from "./components/banner/banner";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/pendis-kemenag.png" />
      </Head>
      <main>
        <div className={styles.base}>
          <Carousel />
          <UnitKerja />
          <Banner />
          <section className="mt-16 mb-16">
            <div className="profil grid grid-cols-2 max-md:grid-cols-1 gap-4">
              <Infografis />
              <Profile />
            </div>
          </section>
          <ReccentArticle />
          <ReccentGaleri />
          <MediaSosial />
          <Layanan />
          <Data />
          <Beasiswa />
          <Publikasi />
        </div>
      </main>
    </>
  );
}
